music-web-store/music-web-store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from main.views import HomePageView, CategoryDetailsView, SubCategoryView,\
    ShoppingCartView, ShoppingCartCheckoutView, \
    ShoppingCartRemoveProductView, ShoppingCartPaymentView, \
    ShoppingCartSummaryView, ShoppingCartSuccessView, NewsletterView, \
    ComplaintView
from products.views import ProductView
from users.views import RegistrationView, LoginView, LogoutView, \
    UserPanelView, UserPanelEditView, PasswordResetView, UserPanelOrdersView, \
    UserPanelWalletRefillView, UserPanelWalletWithdrawView, PasswordResetVerificationView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view()),
    path('newsletter/', NewsletterView.as_view()),
    path('complaint/', ComplaintView.as_view()),
    path('product/<int:product_id>/', ProductView.as_view()),
    path('category/<int:category_id>/', CategoryDetailsView.as_view()),
    path('subcategory/<int:subcategory_id>/', SubCategoryView.as_view()),
    path('users/register/', RegistrationView.as_view()),
    path('users/login/', LoginView.as_view(), name="login-page"),
    path('users/logout/', LogoutView.as_view()),
    path('users/panel/<int:user_id>/', UserPanelView.as_view()),
    path('users/edit/<int:user_id>/', UserPanelEditView.as_view()),
    path('users/panel/orders/<int:user_id>/', UserPanelOrdersView.as_view()),
    path('users/password_reset/', PasswordResetView.as_view()),
    path('users/password-reset-verification/<uidb64>/<token>/', PasswordResetVerificationView.as_view(),
         name='password-reset-verification'),
    path('users/wallet/<int:user_id>/refill/', UserPanelWalletRefillView.as_view()),
    path('users/wallet/<int:user_id>/withdraw/', UserPanelWalletWithdrawView.as_view()),
    path('shopping_cart/<int:user_id>/', ShoppingCartView.as_view()),
    path('shopping_cart/<int:user_id>/checkout/', ShoppingCartCheckoutView.as_view()),
    path('shopping_cart/remove/<int:user_id>/<int:product_id>/', ShoppingCartRemoveProductView.as_view()),
    path('shopping_cart/<int:user_id>/<int:order_id>/payment/', ShoppingCartPaymentView.as_view()),
    path('shopping_cart/<int:user_id>/<int:order_id>/summary/', ShoppingCartSummaryView.as_view()),
    path('shopping_cart/<int:user_id>/<int:order_id>/success/', ShoppingCartSuccessView.as_view())

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music-web-store/main/models.py
from django.db import models
from users.models import WebsiteUser
from products.models import Product


class Category(models.Model):
    """
    Stores information about categories
    """
    objects = None
    name = models.CharField(max_length=500)
    description = models.TextField()

    def __str__(self):
        return self.name


class CategorySubCategory(models.Model):
    """
    Creates a relation between categories and subcategories, allowing a subcategory to belong to a category
    :model Category:
    :model SubCategory:
    """
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey('SubCategory', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category}->{self.subcategory}'


class SubCategory(models.Model):
    """
    Stores information about subcategories
    """
    name = models.CharField(max_length=500)
    description = models.TextField()
    category_id = models.ManyToManyField(Category, through=CategorySubCategory)
    image = models.ImageField(upload_to='img', null=True)

    def __str__(self):
        return self.name


class ShoppingCart(models.Model):
    """
    Stores information about shopping carts(each user has his own shopping cart)
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(WebsiteUser, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.user}, {self.product}, {self.quantity}'


class ProductOrder(models.Model):
    """
    Creates a relation between products and orders,
    allowing to store information about which products were chosen in a specific order
    :model Product:
    :model Order:
    """
    user = models.ForeignKey(WebsiteUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.user}, {self.product}, {self.order}'


class Order(models.Model):
    """
    Stores information about orders(each user has his own orders)
    """
    user = models.ForeignKey(WebsiteUser, on_delete=models.CASCADE)
    product_ordered = models.ManyToManyField(Product, through=ProductOrder)
    datetime_ordered = models.DateTimeField(auto_now_add=True)
    amount_paid = models.FloatField(null=True)
    discount_code = models.ForeignKey("DiscountCode", on_delete=models.CASCADE, null=True)
    status_choices = (
        (1, 'Information about the order received'),
        (2, 'Order packaging in progress'),
        (3, 'Order sent to customer'),
        (4, "Order finished")
    )
    status = models.IntegerField(choices=status_choices, null=True, default=1)
    delivery_choices = (
        (1, 'Pickup in person'),
        (2, 'Home shipping')
    )
    shipping_type = models.IntegerField(choices=delivery_choices, default=1)
    payment_choices = (
        (1, 'Cash'),
        (2, 'Credit card'),
        (3, 'Bank transfer'),
        (4, 'Wallet')
    )
    payment_type = models.IntegerField(choices=payment_choices, null=True)
    address = models.CharField(max_length=250, null=True)
    phone_number = models.IntegerField(null=True)

    def __str__(self):
        return f'{self.user}, {self.datetime_ordered}'


class Complaint(models.Model):
    """
    Stores information about complaints
    """
    user = models.ForeignKey(WebsiteUser, on_delete=models.CASCADE)
    subject = models.TextField()
    content = models.TextField()
    datetime_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}: {self.subject}'


class Newsletter(models.Model):
    """
    Stores information about users signed to newsletter
    """
    email = models.TextField(null=True)
    datetime_joined = models.DateTimeField(auto_now_add=True)


class DiscountCode(models.Model):
    name = models.TextField()
    discount_percent = models.IntegerField()

    def __str__(self):
        return f"{self.name} ({self.discount_percent})"


class DiscountCodeUsage(models.Model):
    user = models.ForeignKey(WebsiteUser, on_delete=models.CASCADE)
    discount_code = models.ForeignKey(DiscountCode, on_delete=models.CASCADE)

music-web-store/users/forms.py
from django import forms
from django.core.exceptions import ValidationError


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username')
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    email = forms.EmailField(label='E-mail')
    phone_number = forms.IntegerField(label='Phone number(optional)', required=None)
    address = forms.CharField(label='Address(optional)', required=None)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

music-web-store/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from products.models import Product
from main.models import Category, Order, ProductOrder, SubCategory, ShoppingCart
from users.models import WebsiteUser
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from users.forms import RegistrationForm
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from .utils import token_generator
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages


class RegistrationView(View):
    def get(self, request):
        """
        Displays a registration form, allowing a new user to make an account
        :param request:
        :return registration form page:
        """
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        form = RegistrationForm
        return render(request, 'users/registration_form.html', {'all_categories': all_categories,
                                                                'all_subcategories': all_subcategories,
                                                                'form': form
                                                                })

    def post(self, request):
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        form = RegistrationForm(request.POST)
        if form.is_valid() and form.cleaned_data['password'] and form.cleaned_data['password2']:
            if len(form.cleaned_data['password2']) < 8:
                messages.error(request, "Password too short (Min. 8 characters)")
                return redirect('/users/register/')
            elif any(not c.isalnum() for c in form.cleaned_data['password2']) is False \
                or any(c.isupper() for c in form.cleaned_data['password2']) is False \
                or any(c.islower() for c in form.cleaned_data['password2']) is False \
                or any(c.isdigit() for c in form.cleaned_data['password2']) is False:
                messages.error(request, 'The password does not have all special characters'
                                        '(There should be letters, lowercase letters, numbers and special characters)')
                return redirect('/users/register/')
            elif  form.data['password'] != form.data['password2']:
                messages.error(request, "Passwords mismatch")
                return redirect('/users/register/')
            elif WebsiteUser.objects.filter(username=form.cleaned_data['username']):
                messages.error(request, 'A user with the given username already exists')
                return redirect('/users/register/')
            elif WebsiteUser.objects.filter(email=form.cleaned_data['email']):
                messages.error(request, 'A user with the given e-mail already exists')
                return redirect('/users/register/')
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            address = None
            if form.cleaned_data['address']:
                address = form.cleaned_data['address']
            phone_number = None
            if form.cleaned_data['phone_number']:
                phone_number = form.cleaned_data['phone_number']
            user = WebsiteUser.objects.create(username=username, first_name=first_name,
                                              last_name=last_name, email=email,
                                              phone_number=phone_number, address=address)
            user.set_password(password)
            user.save()
            messages.success(request, "Account successfully created!")
            return redirect('/users/login/')
        else:
            return render(request, 'users/registration_form.html', {'form': form,
                                                                    'all_categories': all_categories,
                                                                    'all_subcategories': all_subcategories
                                                                    })


class LoginView(View):
    def get(self, request):
        """
        Displays a login form, allowing a user that already has an account to log in
        :param request:
        :return login form page:
        """
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        return render(request, 'users/login_form.html', {'all_categories': all_categories,
                                                         'all_subcategories': all_subcategories,
                                                         })

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Wrong username or password, try again')
            return redirect('/users/login/')


class LogoutView(View):
    def get(self, request):
        """
        Displays a prompt to make sure that user want's to log out
        :param request:
        :return logout form page:
        """
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        return render(request, 'users/logout_form.html', {'all_categories': all_categories,
                                                          'all_subcategories': all_subcategories,
                                                          })

    def post(self, request):
        logout(request)
        return redirect('/')


class UserPanelView(View):
    def get(self, request, user_id):
        """
        Displays information about the logged user credentials, including the address, phone number etc.
        :param request:
        :param user_id:
        :return user panel page:
        """
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        shopping_cart_list = ShoppingCart.objects.filter(user_id=request.user.id)
        logged_user_id = request.user.id
        if user_id != logged_user_id:
            return redirect(f'/users/panel/{request.user.id}/')
        user = WebsiteUser.objects.get(id=user_id)
        return render(request, 'users/userpanel.html', {'all_categories': all_categories,
                                                        'all_subcategories': all_subcategories,
                                                        'user': user,
                                                        'shopping_cart_list': shopping_cart_list
                                                        })

    def post(self, request, user_id):
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        shopping_cart_list = ShoppingCart.objects.filter(user_id=request.user.id)
        key_word = request.POST.get('key_word')
        product_results = Product.objects.filter(name__icontains=key_word)
        category_results = Category.objects.filter(name__icontains=key_word)
        subcategory_results = SubCategory.objects.filter(name__icontains=key_word)
        return render(request, 'main/search_results.html', {'all_categories': all_categories,
                                                            'all_subcategories': all_subcategories,
                                                            'product_results': product_results,
                                                            'category_results': category_results,
                                                            'subcategory_results': subcategory_results,
                                                            'shopping_cart_list': shopping_cart_list}
                      )


class UserPanelEditView(View):
    def get(self, request, user_id):
        """
        Displays a form allowing the logged user to change his credentials
        :param request:
        :param user_id:
        :return user panel edit page:
        """
        all_categories = Category.objects.all()
        all_subcategories = SubCategory.objects.all().order_by('name')
        shopping_cart_list = ShoppingCart.objects.filter(user_id=request.user.id)
        logged_user_id = request.user.id
        if user_id != logged_user_id:
            return redirect(f'/users/edit/{request.user.id}/')
        else:
            user = WebsiteUser.objects.get(id=user_id)
            return render(request, 'users/userpanel_edit.html', {'all_categories': all_categories,
                                                                 'all_subcategories': all_subcategories,
                                                                 'user': user,
                                                                 'shopping_cart_list': shopping_cart_list})

    def post(self, request, user_id):
        try:
            username = request.POST.get('username')
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            password = request.POST.get('password')
            email = request.POST.get('email')
            phone_number = request.POST.get('phone_number')
            address = request.POST.get('address')
            user = WebsiteUser.objects.get(id=user_id)
            if password != "":

music-web-store/users/templates/users/login_form.html
{%extends 'main/base.html'%}
{%block content%}
    <div class="centerContainer">
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
<h3>Login</h3>
<form method="post">
    {%csrf_token%}
<p>
    Username:<br> <input type="text" name="username"> <br><br>
    Password:<br> <input type="password" name="password"> <br><br>
    <input type="submit" value="Login">
</p>
</form>
{{error_text}}<br><a href="/users/password_reset/">Forgot your password?</a><br>
<a href="/users/register/">Don't have an account yet?</a>
    </div>
{%endblock%}

music-web-store/users/templates/users/logout_form.html
{%extends 'main/base.html'%}
{%block content%}
<div style="text-align: center" class="centerContainer">
<form method="post">
    {%csrf_token%}
<p>
    Are you sure you want to log out?<br>
    <input type="submit" value="Logout">
</p>
</form>
    </div>
{%endblock%}

music-web-store/users/templates/users/new_password_form.html
{%extends 'main/base.html'%}
{%load static%}
{%block content%}
<div class="centerContainer">
      <h2>Reset password</h2>
      {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
      <form method="post">
        {%csrf_token%}
          New password: <input type="password" name="password1"><br><br>
            Repeat new password: <input type="password" name="password2"><br><br>
          <input type="submit" value="Send">
      </form>
</div>
{%endblock%}

music-web-store/users/templates/users/password_reset.html
{%extends 'main/base.html'%}
{%block content%}
<div class="centerContainer">

<h3>Password reset</h3>
<form method="post">
    {%csrf_token%}
    Your e-mail:<br> <input type="text" name="email"><br><br>
    <input type="submit" value="Send">
</form>
    </div>
{%endblock%}

music-web-store/users/templates/users/registration_form.html
{%extends 'main/base.html'%}
{%block content%}
<div class="centerContainer">
    <div class="formHeader" style="text-align: center"><h2>Register</h2></div>
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
<form method="post" style="padding: 25px">
{%csrf_token%}
  {{form.as_p}}
  <input type="submit" value="Send">

</form>
<a href="/users/login/">Already have an account?</a>
    </div>
{%endblock%}

music-web-store/users/templates/users/userpanel.html
{%extends 'main/base.html'%}
{%block content%}
<div class="userPanelContainer">
<h3>User panel</h3><br>
Username: {{user}} <br><br>
First name: {{user.first_name}}<br><br>
Last name: {{user.last_name}}<br><br>
E-mail: {{user.email}}<br><br>

{%if user.phone_number == None%}
Phone number: <br><br>
{%else%}
Phone number: {{user.phone_number}} <br><br>
{%endif%}

{%if user.address == None%}
Address: <br><br>
{%else%}
Address: {{user.address}} <br><br>
{%endif%}
Wallet: ${{user.wallet}}
<a href="/users/wallet/{{user.id}}/refill/"><b>Refill wallet</b></a>
<b>|</b>
<a href="/users/wallet/{{user.id}}/withdraw/"><b>Withdraw</b></a> <br><br>
<div class="userPanel_button"><a href="/users/edit/{{user.id}}/">Edit</a></div>
<div class="userPanel_button"><a href="/users/panel/orders/{{user.id}}/">My orders</a></div>
</div>
{%endblock%}

music-web-store/users/templates/users/userpanel_edit.html
{%extends 'main/base.html'%}
{%block content%}
<div class="userPanelContainer">
<h3>Edit {{user}}</h3> <h4>{{error_text}}</h4>
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
<form method="post">
    {%csrf_token%}
    Username: <input type="text" value="{{user}}" name="username"><br><br>
    First name: <input type="text" value="{{user.first_name}}" name="first_name"><br><br>
    Last name: <input type="text" value="{{user.last_name}}" name="last_name"><br><br>
    Password: <input type="password" name="password"><br><br>
    E-mail: <input type="text" value="{{user.email}}" name="email"><br><br>
    {%if user.phone_number == None%}
    Phone number: <input type="text" value="" name="phone_number"><br><br>
    {%else%}
    Phone number: <input type="text" value="{{user.phone_number}}" name="phone_number"><br><br>
    {%endif%}
    {%if user.address == None%}
    Address: <input type="text" value="" name="address"><br><br>
    {%else%}
    Address: <input type="text" value="{{user.address}}" name="address"><br><br>
    {%endif%}
    <input type="submit" value="Save">
</form>
</div>
{%endblock%}

music-web-store/users/templates/users/userpanel_orders.html
{%extends 'main/base.html'%}

{%block content%}

<div class="userPanelContainer">

<h3>My orders</h3><br>

{%for order in orders%}

 {%if order.payment_type%}
  <div>

&nbsp;- Order nr <b>{{order.id}}</b><br><br>
Products bought: {%for product_order in product_orders%}
 {%if product_order.order.id == order.id%}<a href="/product/{{product_order.product.id}}/">{{product_order.product}}, </a>{%endif%}
{%endfor%}<br><br>
Status: {{order.get_status_display}}<br><br>
Shipping: {{order.get_shipping_type_display}}<br><br>
Address: {{order.address}}<br><br>
Phone number: {{order.phone_number}}<br><br>
Payment method: {{order.get_payment_type_display}}<br><br>
Amount paid: {{order.amount_paid}}$<br><br><br>--------<br><br><br>

   </div>

 {%endif%}

{%endfor%}<br><br>

<div class="userPanel_button"><a href="/users/panel/{{user.id}}/">Go back</a></div>

</div>

{%endblock%}

music-web-store/users/templates/users/userpanel_wallet_refill.html
{%extends 'main/base.html'%}
{%block content%}
<div class="centerContainer">
<h3>Refill your wallet, {{user}}</h3> <h4>{{error_text}}</h4>
Current amount: <b>${{wallet}}</b>
<form method="post">
    {%csrf_token%}<br>
    Amount: <input type="number" name="amount"><br><br>
    <input type="submit" value="Refill">
</form>
</div>
{%endblock%}

music-web-store/users/templates/users/userpanel_wallet_withdraw.html
{%extends 'main/base.html'%}
{%block content%}
<div class="centerContainer">
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
<h3>Withdraw from your wallet, {{user}}</h3> <h4>{{error_text}}</h4>
Current amount: <b>${{wallet}}</b>
<form method="post">
    {%csrf_token%}<br>
    Amount: <input type="number" name="amount"><br><br>
    <input type="submit" value="Withdraw">
</form>
</div>
{%endblock%}